# * {Prefix} will be replaced by SetEnvPrefix
# * [ARN] tagged fields' value can be an ARN or can be a SSM object
#   ex, --config arn:aws..:parameter/test/patrasche/config
#        or
#       --config.region ap-northeast-2
#       --config.parameter test/patrasche/config

patrasche:
  # logging
  #   level: fatal, error, warn, info, debug or disable
  #
  # {Prefix}_PATRASCHE_LOGGING_LEVEL=debug
  # --patrasche.logging.level debug
  logging:
    level: debug 

  # block [ARN]
  #   if it is a number, it's starting block number. not set = newest
  #
  # {Prefix}_PATRASCHE_BLOCK=6050
  # --patrasche.block 6050
  # block: 5692
  #
  #   if it is a filepath or a AWS resource, it's a 'keep'
  #   'keep' is a storage the current proccessing block number.
  #
  # {Prefix}_PATRASCHE_BLOCK=./BLOCKNUMBER
  # --patrasche.block arn:aws..:test/patrasche/worker-001/block
  block: BLOCKNUMBER

  # channel
  #   channel name
  #
  # {Prefix}_PATRASCHE_CHANNEL=milk
  # --patrasche.channel milk
  channel: milk

  # follow
  #   following next blocks
  #
  # {Prefix}_PATRASCHE_FOLLOW=true
  # --patrasche.follow
  follow: false

  # tx
  #   type: type filter, (ex, 3 or ENDORSER_TRANSACTION)
  #            0: "MESSAGE",
  #            1: "CONFIG",
  #            2: "CONFIG_UPDATE",
  #            3: "ENDORSER_TRANSACTION",
  #            4: "ORDERER_TRANSACTION",
  #            5: "DELIVER_SEEK_INFO",
  #            6: "CHAINCODE_PACKAGE",
  #            8: "PEER_ADMIN_OPERATION",
  #   id: id filter pattern
  #
  # {Prefix}_PATRASCHE_TX_TYPE=3
  # {Prefix}_PATRASCHE_TX_ID="^[89abcdef]"
  # --patrasche.tx.type ENDORSER_TRANSACTION
  # --patrasche.tx.id "^[89abcdef]"
  tx:
    type: ENDORSER_TRANSACTION

  # network [ARN]
  #   network config file path or ARN
  #
  # {Prefix}_PATRASCHE_NETWORK=./config/network.yaml
  # --patrasche.network arn:aws:secretsmanager:region:account-id:secret:test/patrasche/network.yaml
  network: ./config/network.yaml

  # identity [ARN]
  #   username of crytostore, msp path or ARN
  #
  # {Prefix}_PATRASCHE_IDENTITY=patrasche-001
  # --patrasche.identity arn:aws:secretsmanager:region:account-id:secret:test/patrasche/identity.yaml
  identity: ./test/users/patrasche-001/msp
